program ERPThR;



uses
  Forms,
  uLogin in 'uLogin.pas' {fLogin},
  uMenu in 'uMenu.pas' {fMenu},
  uDM in 'uDM.pas' {DM: TDataModule},
  uFuncao in 'uFuncao.pas' {fFuncao},
  envioEmail in 'envioEmail.pas',
  uCadPadrao in 'uCadPadrao.pas' {fCadPadrao},
  uDmImg in 'uDmImg.pas' {DmImg: TDataModule},
  uCadCli in 'uCadCli.pas' {fCadCli},
  uCadMenu in 'uCadMenu.pas' {fCadMenu},
  uSobre in 'uSobre.pas' {fSobre},
  uCadTpUser in 'uCadTpUser.pas' {fCadTpUser},
  uCadCxMaster in 'uCadCxMaster.pas' {fCadCxMaster},
  UCadFornecedor in 'UCadFornecedor.pas' {fCadFornecedor},
  uCadParametro in 'uCadParametro.pas' {fCadParametro},
  uCadMateriaPrima in 'uCadMateriaPrima.pas' {fCadMateriaPrima},
  uCadFunc in 'uCadFunc.pas' {fCadFunc},
  uCadProcesso in 'uCadProcesso.pas' {fCadProcesso},
  uCadProduto in 'uCadProduto.pas' {fCadProduto},
  uCadSemiAcabado in 'uCadSemiAcabado.pas' {fCadSemiAcabado},
  uBotoes in 'uBotoes.pas' {fBotoes},
  uCnsOP in 'uCnsOP.pas' {fCnsOP},
  uCnsRomaneio in 'uCnsRomaneio.pas' {fCnsRomaneio},
  uNovaOP in 'uNovaOP.pas' {fNovaOP},
  uIniciaProducao in 'uIniciaProducao.pas' {fIniciaProducao},
  uLancaProducao in 'uLancaProducao.pas' {fLancaProducao},
  uIniciaMontagem in 'uIniciaMontagem.pas' {fIniciaMontagem},
  uLancaMontagem in 'uLancaMontagem.pas' {fLancaMontagem},
  UCadVendedor in 'UCadVendedor.pas' {fCadVendedor},
  uVenda in 'uVenda.pas' {fVenda},
  uCadCondicao in 'uCadCondicao.pas' {fCadCondicao},
  uGridVenda in 'uGridVenda.pas' {fGridVenda},
  uCReceber in 'uCReceber.pas' {fCReceber},
  uCReceber2 in 'uCReceber2.pas' {fCReceber2},
  uCRecebidas in 'uCRecebidas.pas' {fCRecebidas},
  tbExtenso in 'tbExtenso.pas',
  uBaixaRec in 'uBaixaRec.pas' {fBaixaRec},
  uBxParcial in 'uBxParcial.pas' {fBxParcial},
  uEditarCRec in 'uEditarCRec.pas' {fEditarCRec},
  uImpExtrato in 'uImpExtrato.pas' {fImpExtrato},
  uRenegociacao in 'uRenegociacao.pas' {fRenegociacao},
  uNovoCReceber2 in 'uNovoCReceber2.pas' {fNovoCReceber2},
  uEstorno in 'uEstorno.pas' {fEstorno},
  uCadCusto in 'uCadCusto.pas' {fCadCusto},
  uCADDFixa in 'uCADDFixa.pas' {fCADDFixa},
  uDFixa in 'uDFixa.pas' {fDFixa},
  uCPagarN in 'uCPagarN.pas' {fCPagarN},
  uCPagarN2 in 'uCPagarN2.pas' {fCPagarN2},
  uCPagas in 'uCPagas.pas' {fCPagas},
  uBaixa in 'uBaixa.pas' {fBaixa},
  uNovoCPagar in 'uNovoCPagar.pas' {fNovoCPagar},
  uRelCPagar in 'uRelCPagar.pas' {fRelCPagar},
  uRelCPagas in 'uRelCPagas.pas' {fRelCPagas},
  uRenegociacaoPg in 'uRenegociacaoPg.pas' {fRenegociacaoPg},
  uRelFinanceiro in 'uRelFinanceiro.pas' {fRelFinanceiro},
  uGridCompra in 'uGridCompra.pas' {fGridCompra},
  uPrecoProd in 'uPrecoProd.pas' {fPrecoProd},
  uAjCReceber in 'uAjCReceber.pas' {fAjCReceber},
  uImpressoes in 'uImpressoes.pas' {fImpressoes},
  uCompra in 'uCompra.pas' {fCompra},
  uRelCReceber in 'uRelCReceber.pas' {fRelCReceber},
  uRelCRecebidas in 'uRelCRecebidas.pas' {fRelCRecebidas},
  uRelCompras in 'uRelCompras.pas' {fRelCompras},
  uRelVenProduto in 'uRelVenProduto.pas' {fRelVenProduto},
  uRelVenSat in 'uRelVenSat.pas' {fRelVenSat},
  uRelVenVend in 'uRelVenVend.pas' {fRelVenVend},
  uRelVenRoyalties in 'uRelVenRoyalties.pas' {fRelVenRoyalties},
  uRelVenComissao in 'uRelVenComissao.pas' {fRelVenComissao},
  uValoresReceb in 'uValoresReceb.pas' {fValoresReceb},
  uCADConta in 'uCADConta.pas' {fCADConta},
  uMovCaixa in 'uMovCaixa.pas' {fMovCaixa},
  uImpCaixa in 'uImpCaixa.pas' {fImpCaixa},
  uCADAliqInter in 'uCADAliqInter.pas' {fCADAliqInter},
  uCADNOper in 'uCADNOper.pas' {fCADNOper},
  uCADTransportadora in 'uCADTransportadora.pas' {fCADTransportadora},
  uNF in 'uNF.pas' {fNF},
  uCADClasF in 'uCADClasF.pas' {fCADClasF},
  uFinalidadeNotaDev in 'uFinalidadeNotaDev.pas' {fFinalidadeNotaDev},
  uNFe in 'uNFe.pas' {fNFe},
  uEstoque in 'uEstoque.pas' {fEstoque},
  uImpEstoque in 'uImpEstoque.pas' {fImpEstoque},
  uImpOp in 'uImpOp.pas' {fImpOp},
  uAjPagar in 'uAjPagar.pas' {fAjCPagar},
  uRelEstoque in 'uRelEstoque.pas' {fRelEstoque},
  uRelEstoque_I in 'uRelEstoque_I.pas' {fRelEstoque_I},
  uRelProgramacaoProd in 'uRelProgramacaoProd.pas' {fRelProgramacaoProd},
  uRelOP_I in 'uRelOP_I.pas' {fRelOP_I},
  uRelNF in 'uRelNF.pas' {fRelNF},
  uImpRelNF in 'uImpRelNF.pas' {fImpRelNF},
  uControleCheque in 'uControleCheque.pas' {fControleCheque},
  uVisualizaCheque in 'uVisualizaCheque.pas' {fvisualizaCheque},
  uEscolheStatusCheque in 'uEscolheStatusCheque.pas' {fEscolheStatusCheque},
  uHistoricoCheque in 'uHistoricoCheque.pas' {fHistoricoCheque},
  uRepasse in 'uRepasse.pas' {fRepasse},
  uCheque in 'uCheque.pas' {fCheque},
  uDeposito in 'uDeposito.pas' {fDeposito},
  uImpCheque in 'uImpCheque.pas' {fImpCheque},
  uControleChequeEmitidos in 'uControleChequeEmitidos.pas' {fControleChequeEmitidos},
  uChequeEmitido in 'uChequeEmitido.pas' {fChequeEmitido},
  uCorpo in 'uCorpo.pas' {fCorpo},
  uRellogVenda in 'uRellogVenda.pas' {fRelLogVenda},
  uImpProduto in 'uImpProduto.pas' {fImpProduto},
  uComi_Pagar in 'uComi_Pagar.pas' {fComi_Pagar},
  uNovoComissaoPagar in 'uNovoComissaoPagar.pas' {fNovoComissaoPagar},
  uNovoComiPagar in 'uNovoComiPagar.pas' {fNovoComiPagar},
  uValoresPagarC in 'uValoresPagarC.pas' {fValoresPagarC},
  uComi_Pagas in 'uComi_Pagas.pas' {fComi_Pagas},
  uComi_pagar2 in 'uComi_pagar2.pas' {fComi_Pagar2},
  uCadUniMedida in 'uCadUniMedida.pas' {fCadUniMedida},
  uCadTabela in 'uCadTabela.pas' {fCadTabela},
  uEscolheComissao in 'uEscolheComissao.pas' {fEscolheComissao},
  uCadComercial in 'uCadComercial.pas' {fCadComercial},
  uRelComiPagar in 'uRelComiPagar.pas' {fRelComiPagar},
  uRelComiPagas in 'uRelComiPagas.pas' {fRelComiPagas},
  uCadEmpresa in 'uCadEmpresa.pas' {fCadEmpresa},
  uOrcamento in 'uOrcamento.pas' {fOrcamento},
  uGridOrcamento in 'uGridOrcamento.pas' {fGridOrcamento},
  uEscolheOrc in 'uEscolheOrc.pas' {fEscolheOrc},
  uBuscaProdutoImp in 'uBuscaProdutoImp.pas' {fBuscaProdutoImp},
  uCadRapPro in 'uCadRapPro.pas' {fCadRapPro},
  uClientesWeb in 'uClientesWeb.pas' {fClientesWeb},
  uEscolheStatusPedido in 'uEscolheStatusPedido.pas' {fEscolheStatusPedido},
  uBaixaArquivo in 'uBaixaArquivo.pas' {fBaixaArquivo},
  uCnsBoletos in 'uCnsBoletos.pas' {fCnsBoletos},
  uVenda_Justificativa in 'uVenda_Justificativa.pas' {fVenda_Justificativa},
  uCadSetor in 'uCadSetor.pas' {fCadSetor},
  uExpedicao in 'uExpedicao.pas' {fExpedicao},
  uEscolheEmail in 'uEscolheEmail.pas' {fEscolheEmail},
  uImpCC in 'uImpCC.pas' {fImpCC},
  uInventario in 'uInventario.pas' {fInventario},
  uEnviar in 'uEnviar.pas' {fEnviar},
  uRelCurvaAbc in 'uRelCurvaAbc.pas' {fRelCurvaAbc},
  uRelCurvaABC_I in 'uRelCurvaABC_I.pas' {fRelCurvaAbc_I},
  uDevolucao in 'uDevolucao.pas' {fDevolucao},
  uGridDev in 'uGridDev.pas' {fGridDev},
  uRelClientes in 'uRelClientes.pas' {fRelClientes},
  uImpAniversario in 'uImpAniversario.pas' {fImpAniversario},
  uCadContador in 'uCadContador.pas' {fCadContador},
  ublocoK in 'ublocoK.pas' {fBlocoK},
  uRellogCad in 'uRellogCad.pas' {fRelLogCad},
  uGridOC in 'uGridOC.pas' {fGridOC},
  uOC in 'uOC.pas' {fOC},
  uEscolheOC in 'uEscolheOC.pas' {fEscolheOC},
  uSenhaCad in 'uSenhaCad.pas' {fSenhaCad},
  uSelCheque in 'uSelCheque.pas' {fSelCheque},
  uNF_faturas in 'uNF_faturas.pas' {fNF_faturas},
  uImpRecebimento in 'uImpRecebimento.pas' {fImpRecebimento},
  uNovoProduto in 'uNovoProduto.pas' {fNovoProduto},
  uCadFormas in 'uCadFormas.pas' {fCadFormas},
  uProducaoProgPedido in 'uProducaoProgPedido.pas' {fProducaoProgPedido},
  uCnsSubOP_PorFase in 'uCnsSubOP_PorFase.pas' {fCnsSubOP_PorFase},
  uProducaoProg_Imp in 'uProducaoProg_Imp.pas' {fProducaoProg_Imp},
  uImpMP in 'uImpMP.pas' {fImpMP},
  uImpSA in 'uImpSA.pas' {fImpSA},
  uSelBanco in 'uSelBanco.pas' {fselbanco},
  uMDFe in 'uMDFe.pas' {fMDFe},
  uExpedicaoCial in 'uExpedicaoCial.pas' {fExpedicaoCial},
  uEscolheRelCliente in 'uEscolheRelCliente.pas' {fEscolheRelCliente},
  uImpCliente in 'uImpCliente.pas' {fImpCliente},
  uImpFornec in 'uImpFornec.pas' {fImpFornec},
  uRellogFinan in 'uRellogFinan.pas' {fRelLogFinan},
  uInsereProd in 'uInsereProd.pas' {fInsereProd},
  uNovoSemi in 'uNovoSemi.pas' {fNovoSemi},
  uRelEstoqueAnual in 'uRelEstoqueAnual.pas' {fRelEstoqueAnual},
  uRelEstoqueAnual_I in 'uRelEstoqueAnual_I.pas' {fRelEstoqueAnual_I},
  uRelAjuste in 'uRelAjuste.pas' {fRelAjuste},
  uImpOC in 'uImpOC.pas' {fimpOc},
  uRelSemVendaClientes in 'uRelSemVendaClientes.pas' {fRelSemVendaClientes},
  uAjusteTabela in 'uAjusteTabela.pas' {fAjusteTabela},
  uEntradaCX in 'uEntradaCX.pas' {fEntradaCx},
  uTransferencias in 'uTransferencias.pas' {fTransferencias},
  uImp_finan in 'uImp_finan.pas' {fImp_finan},
  uAbertCaixa in 'uAbertCaixa.pas' {fAbertCaixa},
  uFechamento in 'uFechamento.pas' {fFechamento},
  uVisuCaixa in 'uVisuCaixa.pas' {fVisuCaixa},
  uVisuCaixa_I in 'uVisuCaixa_I.pas' {fVisuCaixa_I},
  uEscolheConta in 'uEscolheConta.pas' {fEscolheConta},
  uVisuCaixaResu_I in 'uVisuCaixaResu_I.pas' {fVisuCaixaResu_I},
  uRelVenCliente in 'uRelVenCliente.pas' {fRelVenCliente},
  uRelVenCliente_I in 'uRelVenCliente_I.pas' {fRelVenCliente_I},
  uRelVenSat_I in 'uRelVenSat_I.pas' {fRelVenSat_I},
  uBuscaCNPJ in 'uBuscaCNPJ.pas' {fBuscaCNPJ},
  uBuscaCPF in 'uBuscaCPF.pas' {fBuscaCPF},
  uRelCRecebidas_I in 'uRelCRecebidas_I.pas' {fRelCRecebidas_I},
  uCadGrupo in 'uCadGrupo.pas' {fCadGrupo},
  uCnsSubOP in 'uCnsSubOP.pas' {fCnsSubOP},
  uProducaoProg in 'uProducaoProg.pas' {fProducaoProg},
  uRelOP in 'uRelOP.pas' {fRelOP},
  uCadTipoCliente in 'uCadTipoCliente.pas' {fCadTipoCliente},
  uBaixaArquivo_I in 'uBaixaArquivo_I.pas' {fBaixaArquivo_I},
  uCadCor in 'uCadCor.pas' {fCadCor},
  uImpRefBase in 'uImpRefBase.pas' {fImpRefBase},
  uImpNutricional in 'uImpNutricional.pas' {fImpNutricional},
  uRelVenPorLote_I in 'uRelVenPorLote_I.pas' {fRelVenPorLote_I},
  uRelVenPorLote in 'uRelVenPorLote.pas' {fRelVenPorLote},
  uImpNutricional_M2 in 'uImpNutricional_M2.pas' {FImpNutricionalM2};

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'ThR Softwares Ltda.';
  Application.CreateForm(TDM, DM);
  Application.CreateForm(TDmImg, DmImg);
  Application.CreateForm(TfMenu, fMenu);
  Application.Run;
end.
